function fitresult = createFit2(x2, y3)
%CREATEFIT(X2,Y3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: x2
%      Y Output: y3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Jan-2024 08:24:36


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x2, y3 );

% Set up fittype and options.
ft = fittype( 'rat22' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.DiffMinChange = 1e-14;
opts.Display = 'Off';
opts.MaxFunEvals = 2000;
opts.MaxIter = 2000;
opts.Normalize = 'off';
opts.Robust = 'Bisquare';
opts.StartPoint = [0.887860955311228 0.842949288995289 0.89879855583219 0.939003091446555 0.815435155938747];
opts.TolFun = 1e-14;
opts.TolX = 1e-14;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
end